### ISSUE TITLE
DSM # 1 - 02-Dec-2018

### ISSUE THREAD

**Issue by syedaSadaf** [syedaSadaf/CodeFathers#2]

**Comment by syedaSadaf** [comment]
BSEF15M052 - 2hrs
1- i worked on [UVA 10305](https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=1246) , planning about preparation
2- Problem was solved by Topological Sort. and it  was easy 
3- I worked on BFS , DFS , Topological Sort  Algorithms 
4- I've problems in recognizing problem category

**Comment by bsef15m053** [comment]
BSEF15M053 0hrs
1. i did not solved any problem
2.I will work on solving problems
